from playwright.sync_api import Playwright, sync_playwright, expect


def test_login_NHBE(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(ignore_https_errors=True)
    page = context.new_page()
    page.goto("https://mcyfronthomo.sis.ad.bia.itau/login")
    page.get_by_label("Usuario").click()
    page.get_by_label("Usuario").fill("nofirmante1")
    page.get_by_label("Usuario").click()
    page.get_by_label("Contraseña").click()
    page.get_by_label("Contraseña").fill("Zz112233")
    page.get_by_label("Contraseña").click()
    page.get_by_role("button", name="Ingresar").click()
    page.get_by_role("link", name="activa menu icon Echeq").click()
    page.get_by_text("Emitidos").click()
    page.get_by_role("button", name="Emitir echeq").click()
    page.get_by_label("Nro. de documento *").click()
    page.get_by_label("Nro. de documento *").fill("33111111133")
    page.get_by_label("Nro. de documento *").click()
    page.get_by_role("button", name="Más detalles seta_baixo").click()
    page.get_by_role("button", name="Menos detalles seta_cima").click()
    page.get_by_role("button", name="Continuar").click()
    page.get_by_role("complementary").filter(has_text="Emitir echeq fechar Datos del beneficiario Razón socialEMPRESA AUT DOSCUIT/CUIL ").click()
    page.get_by_role("combobox", name="Cuenta de origen de los fondos *").click()
    page.get_by_text("CC 0005763-100/5 Saldo ARS").click()
 #   page.get_by_text("CC 0005763-100/5 Saldo ARS 2.688.258.041,28").click()
    page.get_by_label("Motivo de pago *").click()
    page.get_by_label("Motivo de pago *").fill("Fc2341")
    page.get_by_role("complementary").filter(has_text="Emitir echeq fechar Datos del beneficiario Razón socialEMPRESA AUT DOSCUIT/CUIL ").click()
    page.locator("mcy-select").filter(has_text="ARS seta_baixo").click()
    page.get_by_label("Importe *").click()
    page.
    page.get_by_label("Importe *").fill("1,00")
#    page.locator("mcy-amount-input div").filter(has_text="Importe *").nth(3).click()
    page.get_by_role("button", name="Emitir", exact=True).click()
    page.get_by_text("Número de solicitud").click()
#    page.get_by_text("19734").click()
    page.get_by_text("Destinatario").click()
    page.get_by_text("Importe").click()
    page.get_by_text("EMPRESA AUT DOS").click()
    page.get_by_text("ARS 1,00").click()
    page.get_by_text("Fecha de solicitud").click()
    page.get_by_text("Fecha de pago").click()
#    page.get_by_text("15 MAY 2024 11:52").click()
#    page.get_by_text("15 MAY 2024", exact=True).click()


    # ---------------------
    context.close()
    browser.close()
