from playwright.sync_api import Playwright, sync_playwright, expect

def test_login_NHBE(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(ignore_https_errors=True)
    page = context.new_page()
    page.goto("https://mcyfronthomo.sis.ad.bia.itau/login")
    page.locator(".mat-form-field-infix").first.click()
    page.get_by_label("Usuario").fill("nofirmante1")
    page.locator("#login-page__form div").filter(has_text="Contraseña").nth(4).click()
    page.get_by_label("Contraseña").fill("Zz112233")
    page.get_by_role("button", name="Ingresar").click()
 #   page.get_by_text("Actualizar").click()
    page.get_by_role("link", name="activa menu icon Echeq").click()
    page.get_by_text("Emitidos").click()
    page.get_by_role("button", name="Emitir echeq").click()
    page.locator("mcy-echeck-issued-beneficiary mcy-input div").filter(has_text="Nro. de documento *").nth(3).click()
    page.get_by_label("Nro. de documento *").fill("33111111133")
#    page.wait_for_timeout(3000)
    page.get_by_role("button", name="Continuar").click()
    page.get_by_label("Importe *").click()
    page.get_by_label("Importe *").type("1,00")
 #   page.wait_for_timeout(3000)
    page.get_by_text("seta_baixo Cuenta de origen de los fondos *").click()
    page.get_by_text("CC 0005763-100/5").click()
    page.get_by_label("Motivo de pago *").click()
    page.get_by_label("Motivo de pago *").fill("Fc 2463")
 #   page.wait_for_timeout(3000)
    page.get_by_role("button", name="Emitir", exact=True).click()
    page.get_by_text("Número de solicitud").click()
    page.get_by_text("Destinatario").click()
    page.get_by_text("EMPRESA AUT DOS").click()
    page.get_by_text("Importe").click()
    page.get_by_text("Fecha de solicitud").click()
    page.get_by_text("Fecha de pago").click()


    # ---------------------
    context.close()
    browser.close()
