from playwright.sync_api import Playwright, sync_playwright, expect
def test_CPT_T155(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(ignore_https_errors=True)
    page = context.new_page()
    page.goto("https://sapfiorihw11.sis.ad.bia.itau:8021/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html#Shell-home")
    page.locator("xpath=(//div[@class='sapMGTHdrContent OneByOne'][contains(.,'Visi')and contains(.,' 360')])[1]").click()
#    page.get_by_role("button", name="Visión 360°", exact=True).click()
    page.get_by_role("textbox", name="Número de Documento").click()
    page.get_by_role("textbox", name="Número de Documento").fill("31456022")
    page.get_by_role("textbox", name="Número de Documento").click()
    page.get_by_text("BuscarIr").click()
    page.wait_for_timeout(2000)
    page.get_by_text("Paquetes y cuentas").click()
    page.wait_for_timeout(2000)
    page.get_by_role("menuitemradio", name="cuentas").click()
    page.wait_for_timeout(2000)
    page.locator("[id=\"__xmlview16\"]").click()
#    page.wait_for_timeout(2000)
#    page.locator("xpath=//span[contains(@data-sap-ui,'__text95-__xmlview16--tblCuentas-2')]").click()
#    page.get_by_text("0003271-301/9").click()
    page.wait_for_timeout(2000)
    page.get_by_role("menuitemradio", name="Movimientos", exact=True).click()
    page.wait_for_timeout(2000)
    page.get_by_role("toolbar", name="Lista de movimientos").click()
    page.wait_for_timeout(2000)
#    page.locator("[id=\"__xmlview21\"]").click()
    page.wait_for_timeout(2000)
#    page.get_by_role("row", name="07/05/2024 IVA 21% 10.016.911,54").get_by_text("07/05/2024").click()
#    page.get_by_role("row", name="Línea 1 de 10 Fecha 07/05/2024 Concepto IVA 21% Débito -77,49 Entrada no válida Crédito Saldo 10.016.911,54").get_by_text("IVA 21%").click()
#    page.get_by_role("row", name="Línea 1 de 10 Fecha 07/05/2024 Concepto IVA 21% Débito -77,49 Entrada no válida Crédito Saldo 10.016.911,54").get_by_text("-77,49").click()
#    page.get_by_role("cell", name="10.016.911,54").get_by_text("10.016.911,54").click()
    page.wait_for_timeout(2000)

    # ---------------------
    context.close()
    browser.close()


