from playwright.sync_api import Playwright, sync_playwright, expect
def test_CPT_T155(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(ignore_https_errors=True)
    page = context.new_page()
    page.goto("https://sapfiorihw11.sis.ad.bia.itau:8021/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html#Shell-home")
    page.locator("xpath=(//div[@class='sapMGTHdrContent OneByOne'][contains(.,'Visi')and contains(.,' 360')])[1]").click()
#    page.get_by_role("button", name="Visión 360°", exact=True).click()
    page.get_by_role("textbox", name="Número de Documento").click()
    page.get_by_role("textbox", name="Número de Documento").fill("31456022")
    page.get_by_role("textbox", name="Número de Documento").click()
    page.get_by_text("BuscarIr").click()
    page.get_by_text("Paquetes y cuentas").click()
#    page.locator("div").filter(has_text=re.compile(r"^Raiz 0003271$")).click()
#    page.get_by_text("Paquetes y cuentas", exact=True).click()
    page.get_by_role("menuitemradio", name="cuentas").click()
    page.get_by_text("0003271-301/9").click()
    page.get_by_role("menuitemradio", name="Movimientos", exact=True).click()
    page.get_by_text("Lista de movimientos").click()
    page.get_by_role("row", name="Fecha Concepto Débito Crédito Saldo").get_by_text("Fecha").click()
    page.get_by_role("application", name="Lista de movimientos Lista de tabla").get_by_text("Concepto").click()
    page.get_by_role("application", name="Lista de movimientos Lista de tabla").get_by_text("Débito").click()
    page.get_by_role("application", name="Lista de movimientos Lista de tabla").get_by_text("Crédito").click()
    page.get_by_role("columnheader", name="Saldo").get_by_text("Saldo").click()
    page.get_by_role("row", name="07/05/2024 IVA 21% 10.016.911,54").get_by_text("07/05/2024").click()
#    page.locator("[id=\"__text197-__xmlview29--tblCtaUltMov-0\"]").click()
#    page.locator("[id=\"__text197-__xmlview29--tblCtaUltMov-0\"]").click()
#    page.locator("[id=\"__text197-__xmlview29--tblCtaUltMov-0\"]").click()
#    page.locator("[id=\"__status1-__xmlview29--tblCtaUltMov-0-text\"]").click()
    page.get_by_role("cell", name="10.016.911,54").get_by_text("10.016.911,54").click()
    page.
    # ---------------------
    context.close()
    browser.close()


