version: "3.8"
services:
  jenkins_master:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
    networks:
      - red_jenk
  ssh-agent1:
    build: .
    container_name: agent1
    networks:
      red_jenk:
        ipv4_address: 172.28.0.2
    ports:
      - "4443:23"
  ssh-agent2:
    build: .
    container_name: agent2
    networks:
      red_jenk:
        ipv4_address: 172.28.0.3
  ssh-agent3:
    build: .
    container_name: agent3
    networks:
      red_jenk:
        ipv4_address: 172.28.0.4
    ports:
     - "4444:22"
  ssh-agent4:
    build: .
    container_name: agent4
    networks:
      red_jenk:
        ipv4_address: 172.28.0.5
    ports: "4445:22"
  ssh-agent5:
    build: .
    container_name: agent5
    networks:
      red_jenk:
        ipv4_address: 172.28.0.6
    ports:
     - "4446:22"
volumes:
  jenkins-home:

networks:
  red_jenk:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1